import { ActiveThreat, Alert, Report, UserProfile } from '@/types';

export const MOCK_USER: UserProfile = {
  id: 'user-1',
  name: 'Alex Martinez',
  level: 'gold_reporter',
  credibilityScore: 847,
  reportCount: 34,
  verifiedReports: 28,
};

export const MOCK_REPORTS: Report[] = [
  {
    id: 'r-1',
    type: 'tornado',
    location: { lat: 36.1627, lng: -86.7816 },
    timestamp: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    userId: 'u-2',
    userName: 'J. Williams',
    userLevel: 'verified_spotter',
    confidence: 91,
    status: 'verified',
    distance: 0.8,
  },
  {
    id: 'r-2',
    type: 'flash_flood',
    location: { lat: 36.1527, lng: -86.7916 },
    timestamp: new Date(Date.now() - 7 * 60 * 1000).toISOString(),
    userId: 'u-3',
    userName: 'S. Chen',
    userLevel: 'silver_reporter',
    confidence: 74,
    status: 'developing',
    distance: 1.2,
  },
  {
    id: 'r-3',
    type: 'extreme_wind',
    location: { lat: 36.1700, lng: -86.7750 },
    timestamp: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    userId: 'u-4',
    userName: 'R. Johnson',
    userLevel: 'bronze_reporter',
    confidence: 62,
    status: 'observation',
    distance: 0.4,
  },
  {
    id: 'r-4',
    type: 'large_hail',
    location: { lat: 36.1450, lng: -86.8000 },
    timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    userId: 'u-5',
    userName: 'M. Davis',
    userLevel: 'gold_reporter',
    confidence: 88,
    status: 'verified',
    distance: 2.1,
  },
  {
    id: 'r-5',
    type: 'severe_storm',
    location: { lat: 36.1800, lng: -86.7600 },
    timestamp: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
    userId: 'u-6',
    userName: 'K. Thompson',
    userLevel: 'verified_first_responder',
    confidence: 95,
    status: 'immediate_danger',
    distance: 3.4,
  },
];

export const MOCK_THREATS: ActiveThreat[] = [
  {
    id: 't-1',
    type: 'tornado',
    location: { lat: 36.1627, lng: -86.7816 },
    status: 'verified',
    confidence: 91,
    reportCount: 7,
    firstReported: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    lastUpdated: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
    radius: 2.5,
    distance: 0.8,
    reports: MOCK_REPORTS.filter((r) => r.type === 'tornado'),
  },
  {
    id: 't-2',
    type: 'flash_flood',
    location: { lat: 36.1527, lng: -86.7916 },
    status: 'developing',
    confidence: 74,
    reportCount: 4,
    firstReported: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
    lastUpdated: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    radius: 1.8,
    distance: 1.2,
    reports: MOCK_REPORTS.filter((r) => r.type === 'flash_flood'),
  },
  {
    id: 't-3',
    type: 'extreme_wind',
    location: { lat: 36.1700, lng: -86.7750 },
    status: 'observation',
    confidence: 62,
    reportCount: 2,
    firstReported: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    lastUpdated: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    radius: 1.2,
    distance: 0.4,
    reports: MOCK_REPORTS.filter((r) => r.type === 'extreme_wind'),
  },
  {
    id: 't-4',
    type: 'large_hail',
    location: { lat: 36.1450, lng: -86.8000 },
    status: 'verified',
    confidence: 88,
    reportCount: 9,
    firstReported: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    lastUpdated: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    radius: 3.0,
    distance: 2.1,
    reports: MOCK_REPORTS.filter((r) => r.type === 'large_hail'),
  },
  {
    id: 't-5',
    type: 'severe_storm',
    location: { lat: 36.1800, lng: -86.7600 },
    status: 'immediate_danger',
    confidence: 97,
    reportCount: 14,
    firstReported: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    lastUpdated: new Date(Date.now() - 30 * 1000).toISOString(),
    radius: 4.0,
    distance: 3.4,
    reports: [],
  },
];

export const MOCK_ALERTS: Alert[] = [
  {
    id: 'a-1',
    threatId: 't-1',
    type: 'tornado',
    status: 'verified',
    location: { lat: 36.1627, lng: -86.7816 },
    distance: 0.8,
    confidence: 91,
    message: 'Tornado on the ground reported 0.8 miles NW. Seek shelter immediately.',
    timestamp: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    read: false,
  },
  {
    id: 'a-2',
    threatId: 't-3',
    type: 'extreme_wind',
    status: 'observation',
    location: { lat: 36.1700, lng: -86.7750 },
    distance: 0.4,
    confidence: 62,
    message: 'Extreme wind damage reported 0.4 miles N. Trees and power lines down.',
    timestamp: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    read: false,
  },
  {
    id: 'a-3',
    threatId: 't-2',
    type: 'flash_flood',
    status: 'developing',
    location: { lat: 36.1527, lng: -86.7916 },
    distance: 1.2,
    confidence: 74,
    message: 'Flash flooding developing 1.2 miles SW. Avoid low-lying roads.',
    timestamp: new Date(Date.now() - 7 * 60 * 1000).toISOString(),
    read: true,
  },
  {
    id: 'a-4',
    threatId: 't-5',
    type: 'severe_storm',
    status: 'immediate_danger',
    location: { lat: 36.1800, lng: -86.7600 },
    distance: 3.4,
    confidence: 97,
    message: 'Severe storm causing immediate life threat 3.4 miles NE. Emergency responders active.',
    timestamp: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
    read: false,
  },
];

export function computeThreatLevel(threats: ActiveThreat[]): import('@/types').ThreatLevel {
  const nearby = threats.filter((t) => (t.distance ?? Infinity) < 5);
  if (nearby.length === 0) return 'normal';
  if (nearby.some((t) => t.status === 'immediate_danger')) return 'immediate';
  if (nearby.some((t) => t.status === 'verified' && (t.distance ?? Infinity) < 2)) return 'dangerous';
  if (nearby.some((t) => t.status === 'verified')) return 'significant';
  if (nearby.some((t) => t.status === 'developing')) return 'elevated';
  return 'normal';
}
